### ISSUE TITLE
出错运行不了耶

### ISSUE THREAD

**Issue by guiguiluo** [huaisha1224/zhihuCollection_Save#6]
我配置了文件后，点击打包好的exe运行结果是这样的，不知道哪里出了问题，大佬能告诉我么

~~~~本地找不到知乎URL列表~~~~
Traceback (most recent call last):
  File "site-packages\selenium\webdriver\common\service.py", line 76, in start
  File "subprocess.py", line 707, in __init__
  File "subprocess.py", line 990, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "zhihuCollection_Save.py", line 160, in <module>
  File "zhihuCollection_Save.py", line 88, in start_zhihu_question
  File "zhihuCollection_Save.py", line 44, in get_question_url
  File "site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
  File "site-packages\selenium\webdriver\common\service.py", line 83, in start
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

[27272] Failed to execute script zhihuCollection_Save


请按任意键继续. . .

**Comment by huaisha1224** [comment]
看报错提示你需要安装一下 chromedriver.exe
